// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHkSyUV8FUXYusq1QCb1ERY_Vj2DsL-o4',
    appId: '1:172361618330:web:caf79b31934bdc95b36023',
    messagingSenderId: '172361618330',
    projectId: 'scribbles2',
    authDomain: 'scribbles2.firebaseapp.com',
    storageBucket: 'scribbles2.appspot.com',
    measurementId: 'G-0T9TP119EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhRoSuKmH2dazAOQss8EsFUQsNHvaK7iw',
    appId: '1:172361618330:android:b1b6cd254e98c0cab36023',
    messagingSenderId: '172361618330',
    projectId: 'scribbles2',
    storageBucket: 'scribbles2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPG1p1xXhA_wehyRsiep_Upwwe6Fu23Qo',
    appId: '1:172361618330:ios:01a50c70070db226b36023',
    messagingSenderId: '172361618330',
    projectId: 'scribbles2',
    storageBucket: 'scribbles2.appspot.com',
    iosClientId: '172361618330-5c78ad6g82cgoacvk74gftj0e529ov0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.scribbles',
  );
}
