name: earth_imagery_app
description: "An app dedicated to look into daily earth photo at the same position of satelite"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0 #for RESTful apis and parsing the response data
  google_fonts: ^6.1.0 #for font customizations
  hive_flutter: ^1.1.0 #for creating local data sources
  intl: ^0.18.1 #date formats
  hive: ^2.2.3 #for generating hive boxes
  crypto: ^3.0.3 #for creating hashes and digests of password strings
  flutter_snake_navigationbar: ^0.6.1 #custom navigation bar
  url_launcher: ^6.2.1 #leading to browser for webpages
  cached_network_image: ^3.3.0 #caching images for loadtimes
  photo_view: ^0.14.0 #feature to zoom the images
  appwrite: ^11.0.1
  path_provider: ^2.1.1
  location: ^5.0.3
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
