// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvuQTtLqX3mZKZ2t2OPP--qYc7fnTMzG4',
    appId: '1:1029139894402:web:310449dca6bc5c6e1b649b',
    messagingSenderId: '1029139894402',
    projectId: 'bloc-implementation0',
    authDomain: 'bloc-implementation0.firebaseapp.com',
    storageBucket: 'bloc-implementation0.appspot.com',
    measurementId: 'G-DTK9XVCQQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2aW8eKLZvNay6hAXce7_Dke4Hs7VDqiM',
    appId: '1:1029139894402:android:8331d505dbf29f421b649b',
    messagingSenderId: '1029139894402',
    projectId: 'bloc-implementation0',
    storageBucket: 'bloc-implementation0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDycIDgZ8pFA4d0Lr8peV7ixUCRfZYeziY',
    appId: '1:1029139894402:ios:b7360faaf1c6cc3f1b649b',
    messagingSenderId: '1029139894402',
    projectId: 'bloc-implementation0',
    storageBucket: 'bloc-implementation0.appspot.com',
    iosBundleId: 'com.example.blocPhoneAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDycIDgZ8pFA4d0Lr8peV7ixUCRfZYeziY',
    appId: '1:1029139894402:ios:945a529c20384eef1b649b',
    messagingSenderId: '1029139894402',
    projectId: 'bloc-implementation0',
    storageBucket: 'bloc-implementation0.appspot.com',
    iosBundleId: 'com.example.blocPhoneAuthentication.RunnerTests',
  );
}
